//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWebBodySystem.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoRegistro
    {
        public int IdHistorico { get; set; }
        public int IdRegistro { get; set; }
        public int IdMember { get; set; }
        public System.DateTime Fecha { get; set; }
        public string UrlComprobante { get; set; }
        public short IdEstatus { get; set; }
    
        public virtual ctStatusRegistro ctStatusRegistro { get; set; }
        public virtual Registro Registro { get; set; }
    }
}
