//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWebBodySystem.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro()
        {
            this.HistoricoRegistro = new HashSet<HistoricoRegistro>();
            this.RegistroEventos = new HashSet<RegistroEventos>();
            this.ServiciosInteres = new HashSet<ServiciosInteres>();
        }
    
        public int IdRegistro { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Sexo { get; set; }
        public Nullable<byte> IdEdad { get; set; }
        public string Empresa { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> Perfil { get; set; }
        public Nullable<int> IdTipoPase { get; set; }
        public string NombrePase { get; set; }
        public string CostoPase { get; set; }
        public string SubPErfil { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string UrlComprobante { get; set; }
        public Nullable<short> IdEstatus { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ctStatusRegistro ctStatusRegistro { get; set; }
        public virtual Edad Edad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoRegistro> HistoricoRegistro { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroEventos> RegistroEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciosInteres> ServiciosInteres { get; set; }
    }
}
